development: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: {{app_name}}
  database: {{app_name}}_dev
  pool: 5
  timeout: 5000

test:
  << *defaults
  database: {{app_name}}_test
  pool: 5
  timeout: 5000
