source 'https://rubygems.org'

group :web do
  gem 'chaplin', git: 'git://github.com/victormours/chaplin.git'
end

group :lib do
  gem 'pg'
end

group :bin do
  gem 'pry'
end

group :db do
  gem 'activerecord'
  gem 'standalone_migrations'
end

group :development do
  gem 'postmod', git: 'git://github.com/victormours/postmod.git'
  gem 'dotenv'
end
