source 'https://rubygems.org'

gem 'postmod', git: 'git://github.com/victormours/postmod.git'

group :web do
  gem 'chaplin'
end

group :data_store do
  gem 'activerecord'
  gem 'standalone_migrations'
end
